RandomForestClassifier:
  bootstrap: true
  class_weight: null
  criterion: gini
  max_depth: 20
  max_features: sqrt
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 5
  min_samples_split: 10
  min_weight_fraction_leaf: 0.0
  n_estimators: 300
  n_jobs: -1
  oob_score: false
  random_state: 42
  verbose: 0
  warm_start: false
